mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from mysite.views import hello, my_homepage_view, current_datetime, hours_ahead, display_meta, contact, resume, home, nfl_analytics, videos_page
from books import views
import lol.views as lolview

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home),
    url(r'^hello/$', hello),
    url(r'^resume/$', resume),
    url(r'^home/$', home),
    url(r'^nfl/$', nfl_analytics),
    url(r'^time/$', current_datetime),
    url(r'^time/plus/(\d{1,2})/$', hours_ahead),
    url(r'^MetaDisplay/', display_meta),
    url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search),
    url(r'^lolsearch/$', lolview.search),
    url(r'^summoner/(.*)/$', lolview.summoner),
    url(r'^summoner/$', lolview.summoner_landing),
    url(r'^contact/$', contact),
    url(r'^error/$', lolview.error),
    url(r'^videos/$', videos_page),
]

mysite/books/models.py
# Create your models here.
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name ='e-mail')

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

mysite/mysite/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message


class SummonerForm(forms.Form):
    summoner_name = forms.CharField(label='Summoner Name')

mysite/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% load static %}
    <h1>League of Legends Statistics</h1>
    {% block content %}{% endblock %}

    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.
    </p>
    {% endblock %}
</body>
</html>

mysite/templates/base_site.html
<!DOCTYPE html>
<html>
<title>{% block title %}{% endblock %}</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
<body>

{% block navbar %}
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-blue w3-card-2 w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-blue" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/home/" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
    <a href="/resume/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Quote Generator</a>
    <a href="/videos/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">My Videos</a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="/resume/" class="w3-bar-item w3-button w3-padding-large">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-padding-large">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-padding-large">Quote Generator</a>
    <a href="/videos/" class="w3-bar-item w3-button w3-padding-large">My Videos</a>
  </div>
</div>
{% endblock %}
{% load static %}
{% block header %}
{% endblock %}

<div class="w3-row-padding w3-padding-64 w3-container">
    {% block content %}{% endblock %}
</div>

{% block footer %}
<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">
  <div class="w3-xlarge w3-padding-32">
    <a href="https://www.facebook.com/victor.farrell.5"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>
    <a href="https://www.instagram.com/relaxbro12/"><i class="fa fa-instagram w3-hover-opacity"></i></a>
    <a href="https://www.snapchat.com/add/malibuvic"><i class="fa fa-snapchat w3-hover-opacity"></i></a>
    <a href="https://www.youtube.com/channel/UCAjhAVPjPZTmWSwwRhcPVdQ"><i class="fa fa-youtube w3-hover-opacity"></i></a>
    <a href="https://www.linkedin.com/in/victor-farrell-7475b24b/"><i class="fa fa-linkedin w3-hover-opacity"></i></a>
    <a href="https://github.com/jvfarrell"><i class="fa fa-github w3-hover-opacity"></i></a>
 </div>
 <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>
{% endblock %}

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</body>
</html>

mysite/templates/contact_form.html
{% extends "base_site.html" %}
{% block title %}Contact Victor{% endblock %}
{% block content %}

<!-- Contact -->
    <h1 class="w3-xxxlarge w3-text-blue"><b>Contact Me</b></h1>
    <p>Reach out! I'm always down to meet up and chat about projects, code, or just video games.</p>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            <input class="w3-input w3-border" {{ form.subject }}
                   <br>
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
             <input class="w3-input w3-border" {{ form.email }}
                    <br>
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
             <input class="w3-input w3-border" {{ form.message }}
                    <br>
        </div>
        <br>
        {% csrf_token %}
       <button type="submit" class="w3-button w3-block w3-padding-large w3-blue w3-margin-bottom">Send Message</button>
    </form>
{% endblock %}

mysite/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
    <p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/templates/cv.html
{% extends "base.html" %}

{% block title %}Resume / CV{% endblock %}

{% block content %}
<p>
    <iframe src="/static/Victor_Resume_11_2016.pdf" width="100%" height="800px"></iframe>
</p>
{% endblock %}

mysite/templates/footer.html
    <hr>
    <p>Thanks for visiting my site.</p>
    </body>
</html>

mysite/templates/header.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html lang="en">

<head>

mysite/templates/lol_search_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Summoner Search</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="/lolsearch/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/templates/nfl_analytics.html
{% extends "base_site.html" %}

{% block title %}NFL Data Analytics{% endblock %}
{% block header %}

<header class="w3-container w3-green w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">IN PROGRESS</h1>
  <p class="w3-xlarge">still working on this piece...stay tuned</p>
</header>

{% endblock %}

mysite/templates/search_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/templates/search_results.html
<!DOCTYPE html>
<html>
    <head>
    <title>Book Search</title>
    </head>
    <body>
        <p>You searched for: <strong>{{ query }}</strong></p>

        {% if books %}
            <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
            <ul>
                {% for book in books %}
                <li>{{ book.title }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No books matched your search criteria.</p>
        {% endif %}
    </body>
</html>

mysite/templates/summoner_landing_page.html
{% extends "base_site.html" %}

{% block title %}Summoner Lookup{% endblock %}
{% block navbar %}
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-blue w3-card-2 w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-blue" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/home/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Home</a>
    <a href="/resume/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-padding-large w3-white">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Quote Generator</a>
    <a href="/nfl/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">NFL Analytics</a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="/resume/" class="w3-bar-item w3-button w3-padding-large">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-padding-large">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-padding-large">Quote Generator</a>
    <a href="/nfl/" class="w3-bar-item w3-button w3-padding-large">NFL Analytics</a>
  </div>
</div>
{% endblock %}
{% block header %}
<style>
.loader {
  border: 8px solid #4d94ff;
  border-radius: 50%;
  border-top: 8px solid #ff9900;
  width: 40px;
  height: 40px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
<header class="w3-container w3-light-gray w3-center" style="padding:15% 16px">
    <h1 class="w3-xxxlarge w3-text-blue" style="centered=true"><b>League of Legends Profile</b></h1>
    <script type="text/javascript">
        function lookup() {
            var name = document.getElementById('summoner_name').value;
            window.location = "http://127.0.0.1:8000/summoner/" + name;
        }
    </script>

    <center>
        <form action="" method="post" onsubmit="move()">
            <label for="summoner_name">Summoner Name:</label>
            {{ form.summoner_name }}
            <input type="submit" value="Submit" onclick="move()"/>
            <select class="w3-select" name="option" style="width:50px">
              <option value="1">NA</option>
              <option value="2">Needs</option>
              <option value="3">Implementation</option>
            </select>
            {% csrf_token %}
        </form>
    </center>
    <br>
        <center><div id="loading_wheel" class="loader" style="display:none"></div></center>
    <script>
    function move() {
      document.getElementById("loading_wheel").style.display = "block";
    }
    </script>
</header>

{% endblock %}

mysite/templates/summoner_lookup.html
{% extends "base_site.html" %}
{% block navbar %}
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-blue w3-card-2 w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-blue" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/home/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Home</a>
    <a href="/resume/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-padding-large w3-white">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Quote Generator</a>
    <a href="/nfl/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">NFL Analytics</a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="/resume/" class="w3-bar-item w3-button w3-padding-large">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-padding-large">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-padding-large">Quote Generator</a>
    <a href="/nfl/" class="w3-bar-item w3-button w3-padding-large">NFL Analytics</a>
  </div>
</div>
{% endblock %}
{% block title %}Summoner Lookup{% endblock %}
{% block header %}
<style>
.champ-level {
    position: relative;
    left: 80%;
    top: -40%;
    z-index: 0;
}
.champ-icon {
    z-index: -2;
}
.loader {
  border: 8px solid #4d94ff;
  border-radius: 50%;
  border-top: 8px solid #ff9900;
  width: 40px;
  height: 40px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
#icon-border {
    border: 22px solid transparent;
    padding: 0px;
    -webkit-border-image: url(/static/rank_border/{{highestAchievedSeasonTier}}.png) 30 stretch; /* Safari 3.1-5 */
    -o-border-image: url(/static/rank_border/{{highestAchievedSeasonTier}}.png) 30 stretch; /* Opera 11-12.1 */
    border-image: url(/static/rank_border/{{highestAchievedSeasonTier}}.png) 30 stretch;
}
.ProfileImage {
    display: block;
    width: 100px;
    height: 100px;
    border: 0;
}
.borderImage {
    position: absolute;
    left: 31px;
    top: 148px;
    width: 120px;
    height: 120px;
    background-position: center bottom;
    background-repeat: no-repeat;
}
</style>
<header class="w3-container w3-light-gray w3-center" style="padding:60px 16px">

    <script type="text/javascript">
        function lookup() {
            var name = document.getElementById('summoner_name').value;
            window.location = "http://127.0.0.1:8000/summoner/" + name;
        }
    </script>

    <center>
        <form action="" method="post" onsubmit="move()">
            <label for="summoner_name">Summoner Name:</label>
            {{ form.summoner_name }}
            <input type="submit" value="Submit" onclick="move()"/>
            {% csrf_token %}
        </form>
    </center>
    <br>
    <center><div id="loading_wheel" class="loader" style="display:none"></div></center>
    <script>
    function move() {
      document.getElementById("loading_wheel").style.display = "block";
    }
    </script>

    <div class="w3-row-padding w3-padding-48 w3-theme-l1">

        <!--<div class="w3-row">
          <div class="w3-col w3-container m2 w3-red"><p>Red</p>
            <div class="borderImage" style="background-image: url(/static/rank_border/{{highestAchievedSeasonTier}}.png);"></div>
                <img src="{{icon_url}}" class="ProfileImage" alt="Summoner Icon">
                <!--<img id="icon-border" src="{{ icon_url }}" alt="Summoner Icon">-->
                <!--<h2>{{ summoner_name }}</h2>
                <p>{{ rank }}</p>
                <!--<p>Role Pref: {{main_role}}, {{secondary_role}}</p>-->
                <!--<p>Win Ratio: {{total_win_ratio}}</p>
          </div>
            {% if champ_list %}
                    {% for champ in champ_list %}
          <div class="w3-col w3-container m2 w3-card w3-white">
              <div>
                    <img class='champ-icon' src="{{champ.champ_url}}" alt="{{ champ.name }} Icon" style="width:100%">
                {% if champ.mastery > 4 %}

                    <img class="champ-level" border="0" style="width:20%" src="/static/champMastery/lvl{{ champ.mastery }}-Flag2.png"
                     alt="level {{ champ.mastery }}">
                </div>
                {% endif %}
              <div class="w3-container">
              <h3>{{ champ.name }}</h3>
                  <p>Games Played: {{ champ.games_played }} </p>
                  <p>Win Ratio: {{ champ.win_ratio }}</p>
                  <p>KDA : {{ champ.kda }}</p>
                  <p>Mastery Lvl: {{ champ.mastery }}</p>
              </div>

          </div>
            {% endfor %}
            {% else %}
                There are no ranked games for this summoner.
            {% endif %}
        </div> -->

        <div class="w3-row">
            <div class="w3-col w3-container m2" style="width:16%; text-align:left;">
                <div class="borderImage" style="background-image: url(/static/rank_border/{{highestAchievedSeasonTier}}.png);"></div>
                <img src="{{icon_url}}" class="ProfileImage" alt="Summoner Icon">
                <!--<img id="icon-border" src="{{ icon_url }}" alt="Summoner Icon">-->
                <h2>{{ summoner_name }}</h2>
                <p>{{ rank }}</p>
                <!--<p>Role Pref: {{main_role}}, {{secondary_role}}</p>-->
                <p>Win Ratio: {{total_win_ratio}}</p>
            </div>

            {% if champ_list %}
                    {% for champ in champ_list %}
            <div class="w3-col w3-container m2" style="width:16%;">
                <div class="w3-card-2 w3-white" style="text-align: left;">
                        <div>
                            <img class='champ-icon' src="{{champ.champ_url}}" alt="{{ champ.name }} Icon" style="width:100%">
                        {% if champ.mastery > 4 %}

                            <img class="champ-level" border="0" style="width:20%" src="/static/champMastery/lvl{{ champ.mastery }}-Flag2.png"
                             alt="level {{ champ.mastery }}">
                        </div>
                        {% endif %}
                      <div class="w3-container">
                      <h3>{{ champ.name }}</h3>
                          <p>Games Played: {{ champ.games_played }} </p>
                          <p>Win Ratio: {{ champ.win_ratio }}</p>
                          <p>KDA : {{ champ.kda }}</p>
                          <p>Mastery Lvl: {{ champ.mastery }}</p>
                      </div>
                </div>
            </div>
                    {% endfor %}
            {% else %}
                There are no ranked games for this summoner.
            {% endif %}
        </div>
    </div>
</header>
{% endblock %}
{% block content %}
<center>
    <p style="opacity:0.5; padding-right:20%; padding-left:20%">This site isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of Riot Games or anyone
    officially involved in producing or managing League of Legends. League of Legends and Riot Games
    are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.</p>
</center>
{% endblock %}

mysite/templates/youtube_links.html
{% extends "base_site.html" %}

{% block title %}My Videos{% endblock %}
{% block navbar %}
<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-blue w3-card-2 w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-blue" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="/home/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Home</a>
    <a href="/resume/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Quote Generator</a>
    <a href="/videos/" class="w3-bar-item w3-button w3-padding-large w3-white">My Videos</a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="/resume/" class="w3-bar-item w3-button w3-padding-large">Resume</a>
    <a href="/summoner/" class="w3-bar-item w3-button w3-padding-large">Summoner Lookup</a>
    <a href="/home/#quote" class="w3-bar-item w3-button w3-padding-large">Quote Generator</a>
    <a href="/videos/" class="w3-bar-item w3-button w3-padding-large">My Videos</a>
  </div>
</div>
{% endblock %}
{% block header %}

<header class="w3-container w3-gray w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">Some of my passions:
  </h1>
  <p class="w3-xlarge">League of Legends & Hip Hop Dance</p>
    <!-- Video Grid -->
  <div class="w3-row">
    <div class="w3-half">
      <iframe width="100%" height="315" src="https://www.youtube.com/embed/QLjj6eHv-JA" frameborder="0" allowfullscreen></iframe>
      <iframe width="100%" height="315" src="https://www.youtube.com/embed/sQkS5NIyI3o" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="w3-half">
      <iframe width="100%" height="315" src="https://www.youtube.com/embed/grlwhcvk2XQ" frameborder="0" allowfullscreen></iframe>
      <iframe width="100%" height="315" src="https://www.youtube.com/embed/HE-lngxWv8E" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</header>

{% endblock %}